export const ADD_ENTRY = "ADD_ENTRY"
export const FETCH_ENTRIES = "FETCH_ENTRIES"
export const SIGN_UP = "SIGN_UP"
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
export const LOAD_USER = "LOAD_USER"
